server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~ ^/(new|join|menu|review)$ {
    return 308 $uri/$is_args$args;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
